# Generated by Django 3.0.3 on 2020-02-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='imagen',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to=''),
        ),
    ]
