# Generated by Django 3.0.3 on 2020-02-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_inicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='comentarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
