# Generated by Django 3.0.3 on 2020-02-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fotos',
        ),
    ]
