# Generated by Django 3.0.3 on 2020-02-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_perfil_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fotos',
        ),
    ]
