# Generated by Django 3.0.3 on 2020-02-16 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_perfil_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fotos',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Inicio'),
        ),
    ]
