# Generated by Django 3.0.3 on 2020-02-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_auto_20200216_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fotos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Inicio'),
        ),
        migrations.DeleteModel(
            name='ConjuntoFotos',
        ),
    ]
