# Generated by Django 3.0.3 on 2020-02-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_auto_20200217_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fotos',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Inicio'),
        ),
    ]
