# Generated by Django 3.0.3 on 2020-02-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_perfil_fotos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='fotos',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='conjunto',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='conjunto',
            name='likes',
        ),
        migrations.AddField(
            model_name='inicio',
            name='comentarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inicio',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
