# Generated by Django 3.0.3 on 2020-02-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_auto_20200217_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagenPerfil',
            field=models.ImageField(blank=True, default='camilo.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='infoCuenta',
            field=models.CharField(default='Cuenta nueva', max_length=100),
        ),
        migrations.DeleteModel(
            name='Conjunto',
        ),
    ]
