# Generated by Django 3.0.3 on 2020-02-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_conjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
