# Generated by Django 3.0.3 on 2020-02-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_auto_20200217_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Conjunto',
        ),
    ]
