# Generated by Django 3.0.3 on 2020-02-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_auto_20200219_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Inicio'),
        ),
    ]
