# Generated by Django 3.0.3 on 2020-02-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_auto_20200225_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='comentarios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inicio',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Publicaciones',
        ),
    ]
