# Generated by Django 3.0.3 on 2020-02-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_inicio_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='slug',
        ),
    ]
