# Generated by Django 3.0.3 on 2020-02-26 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_inicio_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='inicio',
            name='descripcion',
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.CharField(blank=True, max_length=100, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Inicio')),
            ],
        ),
    ]
