# Generated by Django 3.0.3 on 2020-02-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0033_auto_20200226_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='likes',
        ),
        migrations.AddField(
            model_name='inicio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
