# Generated by Django 3.0.3 on 2020-03-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0034_auto_20200226_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='likes',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
    ]
