# Generated by Django 3.0.3 on 2020-03-04 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0036_auto_20200304_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='likes',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
