# Generated by Django 3.0.3 on 2020-03-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0037_auto_20200304_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='slug',
        ),
    ]
