# Generated by Django 3.0.3 on 2020-03-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0038_remove_inicio_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagenPerfil',
            field=models.ImageField(blank=True, upload_to='images_perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='infoCuenta',
            field=models.CharField(max_length=100),
        ),
    ]
